//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace AssetDBEmailFunction
{
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
        }

        private string text;
        private string description;
        public string Id { get; set; }

        public string Text
        {
            get
            {
                text = this.Name + "(" + this.AssetTypeValue + ")";
                return text;
            }

            set { text = value; }
        }

        public string Description
        {
            get
            {
                description = this.Status + " - Next service date : " + this.NextServiceDate;
                return description;
            }
            set { description = value; }
        }

        public int AssetID { get; set; }
        public int AssetType { get; set; }
        public int AssetSubType { get; set; }
        public string AssetTypeValue { get; set; }
        public string AssetSubTypeValue { get; set; }
        public string Name { get; set; }
        public string ClientID { get; set; }
        public string LabID { get; set; }
        public string Status { get; set; }
        public string DeviceStatus { get; set; }
        public bool HasAlarm { get; set; }
        public string AlarmMessage { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public string Notes { get; set; }
        public virtual AssetSubType AssetSubType1 { get; set; }
        public virtual AssetType AssetType1 { get; set; }
    }
}
